CREATE TABLE IF NOT EXISTS `ndwr`.`ndwr_all_patient_visits_extract` (
  `PatientPK` INT NOT NULL,
  `PatientID` INT NOT NULL,
  `FacilityID` INT NULL,
  `SiteCode` VARCHAR(45) NOT NULL,
  `Emr` VARCHAR(50) NULL,
  `Project` VARCHAR(50) NULL,
  `FacilityName` VARCHAR(100) NULL,
  `VisitID` INT NULL,
  `VisitDate` DATETIME NULL,
  `Service` VARCHAR(50) NULL,
  `VisitType` VARCHAR(50) NULL,
  `WHOStage` INT NULL,
  `WABStage` INT NULL,
  `Pregnant` VARCHAR(20) NULL,
  `LMP` DATETIME NULL,
  `EDD` DATETIME NULL,
  `Height` INT NULL,
  `Weight` INT NULL,
  `BP` VARCHAR(10) NULL,
  `OI` VARCHAR(200) NULL,
  `OIDate` DATETIME NULL,
  `Adherence` VARCHAR(200) NULL,
  `AdherenceCategory` VARCHAR(200) NULL,
  `SubstitutionFirstlineRegimenDate` DATETIME NULL,
  `SubstitutionFirstlineRegimenReason` VARCHAR(500) NULL,
  `SubstitutionSecondlineRegimenDate` DATETIME NULL,
  `SubstitutionSecondlineRegimenReason` VARCHAR(500) NULL,
  `SecondlineRegimenChangeDate` DATETIME NULL,
  `SecondlineRegimenChangeReason` VARCHAR(500) NULL,
  `FamilyPlanningMethod` VARCHAR(200) NULL,
  `PwP` VARCHAR(200) NULL,
  `GestationAge` INT NULL,
  `NextAppointmentDate` DATETIME NULL,
  `DifferentiatedCare` VARCHAR(50) NULL,
  `KeyPopulationType` VARCHAR(50) NULL,
  `PopulationType` VARCHAR(50) NULL,
  `StabilityAssessment` VARCHAR(50) NULL,
  `DateCreated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   INDEX visit_patient_id (PatientID),
   INDEX visit_patient_pk (PatientPK),
   INDEX visit_facility_id (FacilityID),
   INDEX visit_site_code (SiteCode),
   INDEX visit_visit_date (VisitDate),
   INDEX visit_date_created (DateCreated),
   INDEX visit_patient_visit (PatientID,VisitDate),
   INDEX visit_patient_facility (PatientID,FacilityID)
  );