use ndwr;
select
PatientPK,
PatientID,
FacilityID,
SiteCode,
Emr,
Project,
FacilityName,
VisitID,
VisitDate,
Service,
VisitType,
WHOStage,
WABStage,
Pregnant,
if(LMP,LMP,NULL) as LMP,
if(EDD,EDD,NULL) as EDD,
Height,
Weight,
BP,
OI,
if(OIDate,OIDate,NULL) as OIDate,
Adherence,
AdherenceCategory,
if(SubstitutionFirstlineRegimenDate,SubstitutionFirstlineRegimenDate,NULL) as SubstitutionFirstlineRegimenDate,
SubstitutionFirstlineRegimenReason,
if(SubstitutionSecondlineRegimenDate,SubstitutionSecondlineRegimenDate,NULL) as SubstitutionSecondlineRegimenDate,
SubstitutionSecondlineRegimenReason,
if(SecondlineRegimenChangeDate,SecondlineRegimenChangeDate,NULL) as SecondlineRegimenChangeDate,
SecondlineRegimenChangeReason,
FamilyPlanningMethod,
PwP,
GestationAge,
if(NextAppointmentDate,NextAppointmentDate,date_add(VisitDate,interval 21 day)) as NextAppointmentDate,
DifferentiatedCare,
KeyPopulationType,
PopulationType,
StabilityAssessment from ndwr.ndwr_all_patient_visits_extract;