SELECT 
		    PatientPK,
            SiteCode,
		    PatientID,
		    FacilityID,
		    Emr,
		    Project,
		    FacilityName,
		    ExitDescription,
		    ExitDate,
		    ExitReason,
        TOVerified,
        TOVerifiedDate
		FROM
		    ndwr.ndwr_all_patient_status_extract;