use ndwr;
select 
PatientPK,
PatientID,
FacilityID,
SiteCode,
Emr,
Project,
FacilityName,
DOB,
AgeEnrollment,
AgeARTStart,
AgeLastVisit,
RegistrationDate,
PatientSource,
Gender,
StartARTDate,
PreviousARTStartDate,
PreviousARTRegimen,
StartARTAtThisFacility,
StartRegimen,
IF(StartRegimenLine IS NULL,1,StartRegimenLine) AS `StartRegimenLine`,
LastARTDate,
LastRegimen,
IF(LastRegimenLine IS NULL,1,LastRegimenLine) AS `LastRegimenLine`,
Duration,
if(ExpectedReturn=NULL,date_add(LastVisit,interval 21 day),LastVisit) as ExpectedReturn,
Provider,
LastVisit,
ExitReason,
ExitDate from ndwr.ndwr_patient_art_extract;