use ndwr;
select 
PatientPK,
PatientID,
FacilityID,
SiteCode,
Emr,
Project,
FacilityName,
DOB,
AgeEnrollment,
AgeARTStart,
AgeLastVisit,
if(RegistrationDate<'1997-01-01','1997-01-01',RegistrationDate) as RegistrationDate,
PatientSource,
Gender,
if(StartARTDate<'1997-01-01','1997-01-01',StartARTDate) as StartARTDate,
if(PreviousARTStartDate<'1997-01-01','1997-01-01',PreviousARTStartDate) as PreviousARTStartDate,
PreviousARTRegimen,
StartARTAtThisFacility,
StartRegimen,
StartRegimenLine,
LastARTDate,
LastRegimen,
LastRegimenLine,
Duration,
if(ExpectedReturn=NULL,date_add(LastVisit,interval 21 day),LastVisit) as ExpectedReturn,
Provider,
LastVisit,
ExitReason,
ExitDate from ndwr.ndwr_patient_art_extract;