use ndwr;
SELECT 
    PatientPK,
    PatientID,
    FacilityID,
    SiteCode,
    Emr,
    Project,
    FacilityName,
    Gender,
    DOB,
    RegistrationDate,
    RegistrationAtCCC,
    RegistrationAtPMTCT,
    RegistrationAtTBClinic,
    PatientSource,
    Region,
    District,
    Village,
    ContactRelation,
    LastVisit,
    MaritalStatus,
    EducationLevel,
    CASE
       WHEN DateConfirmedHIVPositive IS NOT NULL THEN IF(DateConfirmedHIVPositive = '1900-01-01','1997-01-01', DateConfirmedHIVPositive)
       ELSE DateConfirmedHIVPositive
    END AS `DateConfirmedHIVPositive`,
    PreviousARTExposure,
    PreviousARTStartDate,
    StatusAtCCC,
    StatusAtPMTCT,
    StatusAtTBClinic,
    SatelliteName,
    Inschool,
    KeyPopulationType,
    Orphan,
    PatientResidentCounty,
    PatientResidentLocation,
    PatientResidentSubCounty,
    PatientResidentSubLocation,
    PatientResidentVillage,
    PatientResidentWard,
    PatientType,
    PopulationType,
    TransferInDate
FROM
    ndwr.ndwr_all_patients_extract;