CREATE TABLE `ndwr`.`ndwr_all_patients_extract` (
  `PatientPK` INT NOT NULL,
  `PatientID` VARCHAR(100) NOT NULL,
  `FacilityID` INT NULL,
  `SiteCode` INT NOT NULL,
  `Emr` VARCHAR(50) NULL,
  `Project` VARCHAR(50) NULL,
  `FacilityName` VARCHAR(100) NULL,
  `Gender` VARCHAR(10) NULL,
  `DOB` DATETIME NULL,
  `RegistrationDate` DATETIME NOT NULL,
  `RegistrationAtCCC` DATETIME NOT NULL,
  `RegistrationAtPMTCT` DATETIME NULL,
  `RegistrationAtTBClinic` DATETIME NULL,
  `PatientSource` VARCHAR(100) NULL,
  `Region` VARCHAR(100) NULL,
  `District` VARCHAR(100) NULL,
  `Village` VARCHAR(100) NULL,
  `ContactRelation` VARCHAR(250) NULL,
  `LastVisit` DATETIME NULL,
  `MaritalStatus` VARCHAR(100) NULL,
  `EducationLevel` VARCHAR(50) NULL,
  `DateConfirmedHIVPositive` DATETIME NULL,
  `PreviousARTExposure` VARCHAR(50) NULL,
  `PreviousARTStartDate` DATETIME NULL,
  `StatusAtCCC` VARCHAR(100) NULL,
  `StatusAtPMTCT` VARCHAR(100) NULL,
  `StatusAtTBClinic` VARCHAR(100) NULL,
  `SatelliteName` VARCHAR(100) NULL,
  `Inschool` VARCHAR(100) NULL,
  `KeyPopulationType` VARCHAR(100) NULL,
  `Orphan` VARCHAR(100) NULL,
  `PatientResidentCounty` VARCHAR(100) NULL,
  `PatientResidentLocation` VARCHAR(100) NULL,
  `PatientResidentSubCounty` VARCHAR(100) NULL,
  `PatientResidentSubLocation` VARCHAR(100) NULL,
  `PatientResidentVillage` VARCHAR(100) NULL,
  `PatientResidentWard` VARCHAR(100) NULL,
  `PatientType` VARCHAR(100) NULL,
  `PopulationType` VARCHAR(100) NULL,
  `TransferInDate` DATETIME NULL);
