CREATE TABLE IF NOT EXISTS ndwr_patient_art_extract (
  `PatientPK` INT NOT NULL,
  `PatientID` INT NOT NULL,
  `FacilityID` INT NOT NULL,
  `SiteCode` INT NULL,
  `Emr` VARCHAR(50) NULL,
  `Project` VARCHAR(50) NULL,
  `FacilityName` VARCHAR(50) NULL,
  `DOB` DATETIME NULL,
  `AgeEnrollment` INT NULL,
  `AgeARTStart` INT NULL,
  `AgeLastVisit` INT NULL,
  `RegistrationDate` DATETIME NULL,
  `PatientSource` VARCHAR(50) NULL,
  `Gender` VARCHAR(50) NULL,
  `StartARTDate` DATETIME NULL,
  `PreviousARTStartDate` DATETIME NULL,
  `PreviousARTRegimen` VARCHAR(50) NULL,
  `StartARTAtThisFacility` VARCHAR(50) NULL,
  `StartRegimen` VARCHAR(50) NULL,
  `StartRegimenLine` VARCHAR(100) NULL,
  `LastARTDate` DATETIME NULL,
  `LastRegimen` VARCHAR(100) NULL,
  `LastRegimenLine` VARCHAR(200) NULL,
  `Duration` INT NULL,
  `ExpectedReturn` INT NULL,
  `Provider` VARCHAR(50) NULL,
  `LastVisit` DATETIME NULL,
  `ExitReason` VARCHAR(100) NULL,
  `ExitDate` DATETIME NULL,
  `DateCreated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   INDEX patient_art_start_date (PatientID , StartARTDate),
   INDEX patient_art_end_date (PatientID , StartARTDate),
   INDEX patient_id (PatientID),
   INDEX facility_id (FacilityID),
   INDEX site_code (SiteCode),
   INDEX patient_pk (PatientPK),
   INDEX art_start_date (StartARTDate),
   INDEX date_created (DateCreated)
);